approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  abr:
    npmAuthToken: "${NIPOTO_NPM_TOKEN}"
    npmRegistryServer: "https://git.services.iranpage.net/api/v4/groups/37/-/packages/npm/"